apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-lpmg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-lpmg
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-lpmg
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-lpmg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-lpmg
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ibjk-tenant/rhtap-demo-app/hacbs-test-project-lpmg@sha256:ff28a6806bd8afb8b5b60c23ccdc8043c42613aa74aa9c6f3c80e7eafca99b0e
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
