apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-lpmg
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ibjk-tenant/rhtap-demo-app/hacbs-test-project-lpmg@sha256:ff28a6806bd8afb8b5b60c23ccdc8043c42613aa74aa9c6f3c80e7eafca99b0e
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
